spring.application.name=social-media

# 伺服器執行的 Port，預設是 8080
server.port=8080

# 資料庫連線設定 (esun_social是我們剛剛建立的資料庫名稱)
spring.datasource.url=jdbc:mysql://localhost:3306/esun_social?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
spring.datasource.username=root
# ↓↓↓這裡請換成你自己的資料庫密碼↓↓↓
spring.datasource.password=mysql1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate 設定
# 顯示執行過程中的 SQL 語法，方便我們初學者除錯
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# 這裡設定為 none，讓 Spring Boot 不要去亂動我們的資料表結構
spring.jpa.hibernate.ddl-auto=none